# Generated by Django 4.0.4 on 2022-05-29 21:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('career', '0002_semester'),
    ]

    operations = [
        migrations.CreateModel(
            name='Folder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('link', models.CharField(max_length=3000)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('id_semester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.semester')),
            ],
            options={
                'verbose_name': 'Carpeta',
                'verbose_name_plural': 'Carpetas',
                'permissions': (('add_folder', 'Agregar Carpeta'), ('change_folder', 'Editar Carpeta'), ('delete_folder', 'Eliminar Carpeta'), ('view_folder', 'Listar Carpetas')),
                'default_permissions': (),
            },
        ),
    ]
