# Generated by Django 4.0.4 on 2022-05-16 01:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Career',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Carrera',
                'verbose_name_plural': 'Carreras',
                'permissions': (('add_career', 'Agregar Carrera'), ('change_career', 'Editar Carrera'), ('delete_career', 'Eliminar Carrera'), ('view_career', 'Listar Carreras')),
                'default_permissions': (),
            },
        ),
    ]
