# Generated by Django 4.0.4 on 2022-05-23 00:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('career', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Semester',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=500)),
                ('description', models.CharField(blank=True, max_length=2000, null=True)),
                ('last_modified', models.DateTimeField(auto_now=True)),
                ('id_career', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='career.career')),
            ],
            options={
                'verbose_name': 'Semestre',
                'verbose_name_plural': 'Semestres',
                'permissions': (('add_semester', 'Agregar Semestre'), ('change_semester', 'Editar Semestre'), ('delete_semester', 'Eliminar Semestre'), ('view_semester', 'Listar Semestre')),
                'default_permissions': (),
            },
        ),
    ]
